[build]
target-dir = "target/gltf_test"

# Linux linker optimization (Fastest: mold, Second: lld)
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=mold",
    "-C", "link-arg=-Wl,--no-keep-memory" # Use less RAM during linking
]

# Windows cross-compilation
[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
